name: Aprendiendo GitHub Actions
run-name: Aprendiendo GitHub Actions

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: definir variables
      run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

    - name: Ejecutar script
      run: python index.py