name: Ejecutar index.py

on: [push]

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Ejecutar script
      run: python index.py